repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1
    hooks:
      - id: yamllint

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.18.1
    hooks:
      - id: markdownlint-cli2

  - repo: local
    hooks:
      - id: repo-lint
        name: repo lint
        entry: make repo-lint
        language: system
        pass_filenames: false
      - id: repo-format-check
        name: repo format check
        entry: make repo-format-check
        language: system
        pass_filenames: false
