project_id          = "mpa-forge-bp-rc"
state_project_id    = "mpa-forge-bp-tfstate"
network_name        = "platform-rc"
subnet_name         = "platform-rc-us-east4"
subnet_cidr         = "10.24.0.0/24"
api_container_image = "us-east4-docker.pkg.dev/mpa-forge-bp-rc/apps/backend-api:sha-placeholder"
global_preset       = "cheap-single-vps"
