name: ci

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  ci:
    uses: mpa-forge/.github/.github/workflows/reusable-ci-infra.yml@816e99050519226be282df48aaa86cc9d40227f9
    with:
      working-directory: "."
      terraform-version: "1.14.5"
